INSERT INTO DOLLAR_CARD (ID, AMOUNT, OWNER) VALUES (20, 250.25, 'mich');
INSERT INTO DOLLAR_CARD (ID, AMOUNT, OWNER) VALUES (21, 20.55, 'mich');
INSERT INTO DOLLAR_CARD (ID, AMOUNT, OWNER) VALUES (22, 150.75, 'mich');
INSERT INTO DOLLAR_CARD (ID, AMOUNT, OWNER) VALUES (23, 20.55, 'mark');
INSERT INTO DOLLAR_CARD (ID, AMOUNT, OWNER) VALUES (24, 150.75, 'ama');